// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zakmujlzcobyiojmqlyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpha211amx6Y29ieWlvam1xbHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTU4ODAsImV4cCI6MjA4OTgzMTg4MH0.QauAK42oKBs9jdKOYWbM3w_t9wSOuwzsDu2cpV87nDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});